### ISSUE TITLE
編譯失敗 關於using CalamityMod;

### ISSUE THREAD

**Issue by nathan60107** [Koibumi/CalamityCN#4]
您好，由於想要把翻譯模組改成繁體的，因此試著編譯了一下，目前差CalamityMod找不到，並且災厄模組也不是開源的，網路上都找不不到類似的檔案，想請問是否能以某些管道提供此檔案或是哪邊可以找到此檔案，在此感謝你們發佈了此翻譯模組。

**Comment by nathan60107** [comment]
@Kcovin @Lastprismer 如果不方便提供也希望能得到一個答覆，tag提醒一下。

**Comment by Lastprismer** [comment]
我们这边直接做一个繁简转换的config吧，方便点

**Comment by nathan60107** [comment]
> 我们这边直接做一个繁简转换的config吧，方便点

非常感謝，由於會有用語上的差異，因此想產生高品質的繁體翻譯首選使用[繁化姬](https://zhconvert.org)，他們有[桌面版](https://github.com/Fanhuaji/Fanhuaji-GUI-by-James1201/releases)可以拖曳資料夾進去批次轉換，或著也可以我來維護繁體部分，代表所有繁體玩家感謝你。

**Comment by Lastprismer** [comment]
现在已经做好了。但确实如你所说，目前仅仅是将简体字直接替换为字库中相应的繁体字，某些地方语义不同还是很要命的
现在的问题在于整个mod内文本是分散的，如果目前要加非直接替换的繁体翻译，一是要把原版中读取文本的函数给改了，二是得做文本整合、方便统一管理和修改
要不暂时先这样，我们去研究一下上面两个问题要怎么解决，会尽快

**Comment by Lastprismer** [comment]
灾厄dll可以通过https://github.com/IVogel/tModUnpacker 这里解包获得。
这边碰到了技术上的问题，转换gettextvalue单机没问题但多人会产生奇怪的bug。要不你还是单独做一个繁体的吧，你们也好维护。

**Comment by nathan60107** [comment]
後來我們順利玩完災厄之後，我也忙到沒什麼時間處理這個，對大多數人來說簡轉繁也夠了，可能就這樣吧，看會不會有其他有心人士出來維護，感謝你的協助。

**Comment by Linnnnnna** [comment]
> 後來我們順利玩完災厄之後，我也忙到沒什麼時間處理這個，對大多數人來說簡轉繁也夠了，可能就這樣吧，看會不會有其他有心人士出來維護，感謝你的協助。

https://github.com/Koibumi/CalamityCN/blob/main/Localization/CalamityMod/zh-hant.text
翻好之后后缀改成hjson就好了 ( 目前没有ldstr文本, 需要kc手动转移 )
( 以及不知道hant是不是繁体文件, 不对的话文件名也可以改 )
